name: spotiflac_android
description: Download Spotify tracks in FLAC using extension providers
publish_to: "none"
version: 4.8.0+138

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # State Management
  flutter_riverpod: ^3.3.2

  # Navigation
  go_router: ^17.3.0

# Storage & Persistence
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  path_provider: ^2.1.6
  path: ^1.9.1
  sqflite: ^2.4.3

# HTTP & Network
  http: ^1.6.0
  connectivity_plus: ^7.3.1

  # UI Components
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.2

  # Material Expressive 3 / Dynamic Color
  dynamic_color: ^1.8.1

  # Permissions
  permission_handler: ^12.0.3

  # File Picker
  file_picker: 12.0.0-beta.7

  # JSON Serialization
  json_annotation: ^4.12.0

  # Utils
  url_launcher: ^6.3.2
  device_info_plus: ^13.2.0
  share_plus: ^13.3.0
  receive_sharing_intent: ^1.9.0
  logger: ^2.7.0

  # FFmpeg for audio conversion
  ffmpeg_kit_flutter_new_full: ^2.4.2
  open_filex: ^4.7.0

  video_player: ^2.13.0

  xml: ^7.0.1

  # Notifications
  flutter_local_notifications: ^22.1.0
  audioplayers: ^6.8.1
  audio_service: ^0.18.19
  audio_session: ^0.2.4
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.15.1
  riverpod_lint: ^3.1.4
  json_serializable: ^6.14.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon.png"
  image_path_android: "icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "icon_foreground_android.png"
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: "icon_foreground_android.png"
  ios_content_mode: scaleAspectFill
  remove_alpha_ios: true
  background_color_ios: "#000000"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

  fonts:
    - family: Google Sans Flex
      fonts:
        - asset: assets/fonts/GoogleSansFlex.ttf
